#!/usr/bin/env bash
set -eo pipefail
# build images defined in the root/PROJECT_HOME docker-compose.yml file
docker-compose build --pull
# add built images to the manifest, using yq to filter away test/profile images
docker-compose config | yq -r ".services[] | select(has(\"profiles\") | not) | .image" | \
  "$PIPELINE_HOME/bin/manifest" artifact add -t docker -
