#!/usr/bin/env bash
# executed from $PROJECT_ROOT by iceburg-ci
set -eo pipefail

docker-compose build --pull

# use docker-compose config to identify services that got built...
#   match only services without a profile (e.g. ignoring test services) and
#   write their image to the build.manifest
docker-compose config | yq -r ".services[] | select(has(\"profiles\") | not) | .image" \
  > "$PIPELINE_ARTIFACTS_PATH/build.manifest"
