version: "3.9"
x-defaults: &ci-defaults
  build:
    context: ./

services:
  check:
    << : *ci-defaults
    command: "hadolint -t error src/Dockerfile"

  build:
    << : *ci-defaults
    command: "ci/steps/build"

  test:
    << : *ci-defaults
    command: "tests/test-images.sh"

  publish:
    << : *ci-defaults
    command: "ci/steps/publish"
