version: "3.9"
x-defaults: &ci-defaults
  build:
    context: ./

services:
  check:
    << : *ci-defaults
    command: hadolint -t error src/Dockerfile

  build:
    << : *ci-defaults
    command: |
      sh -c '
        set -eo pipefail
        # build images defined in the root/PROJECT_HOME docker-compose.yml file
        docker-compose build --pull
        # add built images to the manifest, using yq to filter away test/profile images
        docker-compose config | yq -r ".services[] | select(has(\"profiles\") | not) | .image" | \
          "$PIPELINE_HOME/bin/manifest" artifact add -t docker -
      '

  test:
    << : *ci-defaults
    command: |
      sh -c '
        set -eo pipefail
        echo "coming soon to a theatre near *you*"
      '

  publish:
    << : *ci-defaults
    command: ci/steps/publish
